Design/club
Studentidrettsforbundet/studentidrett-frontend pull request #46
Opened 2020-11-03 15:28 UTC by jennyjyu

Already merged with dev inside branch. This branch includes styling of clubs, groups, teams. Sport cards not included. Also correct font on header

2020-11-03 19:25 UTC, KristofferHaakonsen requested changes
Orker ikke å lese gjennom i kveld :P
Men ser med en gang at snapshot testene feiler, tror du må oppdatere snapshotene :)

2020-11-04 10:37 UTC, KristofferHaakonsen requested changes
Nå funker testene :)
Jeg får fortsatt ingen resultater her, vet ikke om det skyldes denne PRen eller?
![image](https://user-images.githubusercontent.com/32167479/98101141-161d2780-1e92-11eb-9f9d-d250fa60b0ac.png)

2020-11-04 10:56 UTC, jennyjyu commented
> Nå funker testene :)

2020-11-04 11:01 UTC, KristofferHaakonsen requested changes
Nå funker det :)
Men snapshot må oppdateres igjen :P

2020-11-04 11:21 UTC, KristofferHaakonsen approved these changes
Ser bra ut nå :)
Legg gjerne ved skjermbilder ved neste PR, særlig siden dette primært er styling

2020-11-04 11:47 UTC, merged

2020-11-04 11:51 UTC, edvardag reviewed
Det er litt dumt at card klassene har forskjellig implementasjon f. eks. width i regioncard er 100% mens width i groupcard er 240px.

Siden alle Cards skal være mer eller mindre like kunne de kanskje  ha arvet fra en felles Card-klasse? 
Nå kan det være litt vanskelig å oppdatere koden siden det står litt forskjellig på forskjellige steder