temporary breadcrumbs, lacks breadcrumb for sport
Studentidrettsforbundet/studentidrett-frontend pull request #55
Opened 2020-11-04 15:03 UTC by lillesol

Breadcrumbs er implementert, men mangler tester og eventuell styling. 
Breadcrumbs er hardkodet og avhenger sterkt på nåværende url-logikk og redux state
Slik er nåværende utseende: 

![Screenshot 2020-11-04 155416](https://user-images.githubusercontent.com/17408433/98127049-89d12b80-1eb6-11eb-8889-8250228c9bc6.png)
![Screenshot 2020-11-04 155509](https://user-images.githubusercontent.com/17408433/98127066-8d64b280-1eb6-11eb-840a-7003ca09c911.png)
![Screenshot 2020-11-04 155714](https://user-images.githubusercontent.com/17408433/98127071-8f2e7600-1eb6-11eb-9785-47f7a0ceb691.png)
![Screenshot 2020-11-04 155925](https://user-images.githubusercontent.com/17408433/98127314-d6b50200-1eb6-11eb-8608-51a7082feb16.png)
![Screenshot 2020-11-04 155958](https://user-images.githubusercontent.com/17408433/98127319-d9175c00-1eb6-11eb-8ad9-166f00d94cb4.png)

2020-11-04 15:09 UTC, KristofferHaakonsen requested changes
Ser ut som at du må oppdatere snapshots :)

2020-11-04 15:14 UTC, magdalenatran requested changes
Kan du endre "home" til noe annet på norsk?

2020-11-05 10:37 UTC, KristofferHaakonsen requested changes
Jeg har kjørt koden og prøvd meg litt frem, det ser veldig nice ut!
Men så åpnet jeg konsollen og fant en del feilmeldinger

![image](https://user-images.githubusercontent.com/32167479/98230198-2d741780-1f5b-11eb-9459-39765c97dd95.png)
![image](https://user-images.githubusercontent.com/32167479/98230234-3664e900-1f5b-11eb-90a0-521e93620af2.png)

2020-11-05 10:53 UTC, lillesol commented
> Jeg har kjørt koden og prøvd meg litt frem, det ser veldig nice ut!
> Men så åpnet jeg konsollen og fant en del feilmeldinger
> 
> ![image](https://user-images.githubusercontent.com/32167479/98230198-2d741780-1f5b-11eb-9459-39765c97dd95.png)
> ![image](https://user-images.githubusercontent.com/32167479/98230234-3664e900-1f5b-11eb-90a0-521e93620af2.png)

Ja dette er noen feil som kan dukke opp, men når jeg kjører koden, f.eks nå og klikker rundt får jeg ikke disse feilmeldingene.
Vet ikke hva som skal til for å reprodusere feilene heller, da de dukker opp iblant. 
Det var disse feilmeldingene jeg nevnte at jeg trengte hjelp med.

2020-11-05 11:57 UTC, KristofferHaakonsen requested changes
Jeg har fikset hooks rekkefølge feilen.
Det er fortsatt en feil når man går inn på f.eks. abakus.
Kan noen andre ta en titt? :)

Her er feilen, litt lav oppløselig gif (ps. tar noen sekunder før den starter)
![zoom-0](https://user-images.githubusercontent.com/32167479/98239970-0d4b5500-1f69-11eb-8c94-7ff3805d5c4e.gif)

2020-11-05 15:36 UTC, KristofferHaakonsen requested changes
Snapshots må oppdateres :P

2020-11-05 16:11 UTC, KristofferHaakonsen requested changes
Ser bra ut, har 3 kommentarer:

**Kan breadcrumbs legges over knappene?**
![image](https://user-images.githubusercontent.com/32167479/98265508-74790180-1f89-11eb-83f9-1d9a1867107d.png)

**Når jeg klikket meg gjennom litt her og der fikk jeg opp disse**
![image](https://user-images.githubusercontent.com/32167479/98265634-9b373800-1f89-11eb-81d4-a892e4ee56b9.png)

**Går det ann å skrive noen flere tester, med mindre det tar altfor lang tid?** :)
![image](https://user-images.githubusercontent.com/32167479/98265758-c457c880-1f89-11eb-9e0b-26bba07b07b2.png)

2020-11-05 17:39 UTC, eirsture commented
> **Når jeg klikket meg gjennom litt her og der fikk jeg opp disse**
> ![image](https://user-images.githubusercontent.com/32167479/98265634-9b373800-1f89-11eb-81d4-a892e4ee56b9.png)

Disse kommer av at backend-main ikke er helt oppdatert, men når dev og main merges burde disse feilmeldingene forsvinne

2020-11-06 10:50 UTC, KristofferHaakonsen approved these changes
Lag en issue på trello for å lage tester.
Lag en issue på trello for å fikse styling og plassering

2020-11-06 10:52 UTC, magdalenatran approved these changes

2020-11-06 11:12 UTC, merged